(ns gooreplacer.bootstrap
  (:require [cljsjs.react-bootstrap]
            [reagent.core :as r])
  (:require-macros [gooreplacer.macro :refer [bootstrap-comp->reagent]]))

 ;; https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.31.0/react-bootstrap.js
(bootstrap-comp->reagent [Accordion
                          Alert
                          Badge
                          Breadcrumb
                          Breadcrumb.Item
                          Button
                          ButtonGroup
                          ButtonToolbar
                          Carousel
                          Carousel.Caption
                          Carousel.Item
                          Checkbox
                          Clearfix
                          Col
                          Collapse
                          ControlLabel
                          Dropdown
                          Dropdown.ControlledComponent
                          Dropdown.Menu
                          Dropdown.Toggle
                          DropdownButton
                          Fade
                          Form
                          FormControl
                          FormControl.Feedback
                          FormControl.Static
                          FormGroup
                          Glyphicon
                          Grid
                          HelpBlock
                          Image
                          InputGroup
                          InputGroup.Addon
                          InputGroup.Button
                          Jumbotron
                          Label
                          ListGroup
                          ListGroupItem
                          Media
                          Media.Body
                          Media.Heading
                          Media.Left
                          Media.List
                          Media.ListItem
                          Media.Right
                          MenuItem
                          Modal
                          Modal.Body
                          Modal.Dialog
                          Modal.Footer
                          Modal.Header
                          Modal.Title
                          Nav
                          NavDropdown
                          NavItem
                          Navbar
                          Navbar.Brand
                          Navbar.Collapse
                          Navbar.ControlledComponent
                          Navbar.Header
                          Navbar.Toggle
                          Overlay
                          OverlayTrigger
                          PageHeader
                          PageItem
                          Pager
                          Pager.Item
                          Pagination
                          PaginationButton
                          Panel
                          PanelGroup
                          Popover
                          ProgressBar
                          Radio
                          ResponsiveEmbed
                          Row
                          SafeAnchor
                          SplitButton
                          SplitButton.Toggle
                          Tab
                          Tab.Container
                          Tab.Content
                          Tab.Pane
                          Table
                          Tabs
                          Thumbnail
                          Tooltip
                          Well])

